#!/usr/bin/env Rscript
# =============================================================================
# ENT drive-time access map from the Valhalla isochrones generated by
# scripts/valhalla_ent_isochrones.R.
#
# Dissolves the per-practice isochrones into one national coverage polygon per
# drive-time band (30/60/120/180 min) and maps them as nested layers over the
# lower-48 states -> the area of the country within an X-minute drive of ANY
# sampled ENT practice. Also reports the CONUS land-area coverage fraction per
# band (a quantitative access-desert summary).
#
# Output: model_output/isochrones/figS7_ent_drivetime_coverage.png
#         model_output/isochrones/drivetime_coverage_stats.csv
# =============================================================================

suppressPackageStartupMessages({library(sf); library(dplyr); library(ggplot2)})
options(stringsAsFactors = FALSE)
sf::sf_use_s2(FALSE)
outdir <- "model_output/isochrones"

# Use whichever source has the most locations: the final rds (written when the
# batch completes) or the running checkpoint (partial). When the checkpoint is
# ahead, the map is preliminary and labeled as such; re-run after completion to
# get the final version.
final_f <- file.path(outdir, "ent_isochrones.rds")
ckpt_f  <- file.path(outdir, "ent_isochrones_checkpoint.rds")
iso_final <- if (file.exists(final_f)) readRDS(final_f) else NULL
iso_ck    <- if (file.exists(ckpt_f))  dplyr::bind_rows(readRDS(ckpt_f)) else NULL
nloc <- function(x) if (is.null(x)) 0L else length(unique(x$loc_id))
use_ck <- nloc(iso_ck) > nloc(iso_final)
iso    <- if (use_ck) iso_ck else iso_final
PRELIM <- use_ck
suffix <- if (PRELIM) "_preliminary" else ""
cat("loaded", nrow(iso), "isochrone polygons,", nloc(iso), "locations,",
    if (PRELIM) "(PRELIMINARY from checkpoint)" else "(final)",
    "\nbands:", paste(sort(unique(iso$band_min)), collapse = "/"), "min\n")

# CONUS Albers for area + mapping; clip to lower-48
ALBERS <- 5070
us <- sf::st_as_sf(maps::map("state", plot = FALSE, fill = TRUE))
us <- sf::st_transform(sf::st_make_valid(us), ALBERS)
bb <- sf::st_bbox(us)                      # true map extent (avoids clipping)
conus_area_km2 <- as.numeric(sum(sf::st_area(us))) / 1e6

iso <- sf::st_transform(sf::st_make_valid(iso), ALBERS)

# dissolve to one coverage polygon per band (largest band first for layering)
bands <- sort(unique(iso$band_min), decreasing = TRUE)
cov <- lapply(bands, function(b) {
  u <- sf::st_union(iso[iso$band_min == b, ])
  u <- sf::st_intersection(sf::st_make_valid(u), sf::st_union(us))   # clip to land
  data.frame(band = b, geom = sf::st_sfc(u, crs = ALBERS))
})
cov_sf <- do.call(rbind, lapply(cov, function(x) sf::st_sf(band = x$band, geometry = x$geom)))
cov_sf$band <- factor(cov_sf$band, levels = bands)

# coverage stats
stats <- do.call(rbind, lapply(sort(bands), function(b) {
  a <- as.numeric(sf::st_area(cov_sf$geometry[cov_sf$band == b])) / 1e6
  data.frame(band_min = b, covered_km2 = round(a),
             pct_conus_land = round(100 * a / conus_area_km2, 1))
}))
write.csv(stats, file.path(outdir, paste0("drivetime_coverage_stats", suffix, ".csv")), row.names = FALSE)
cat("\nCONUS land within an X-minute drive of a sampled ENT practice:\n")
print(stats, row.names = FALSE)

# map: nested coverage layers over the states
pal <- setNames(c("#440154","#31688e","#35b779","#fde725")[seq_along(bands)],
                as.character(bands))
g <- ggplot() +
  geom_sf(data = us, fill = "grey92", color = "white", linewidth = 0.2) +
  geom_sf(data = cov_sf, aes(fill = band), color = NA, alpha = 0.85) +
  geom_sf(data = us, fill = NA, color = "white", linewidth = 0.2) +
  scale_fill_manual(values = pal, name = "Drive time (min)",
                    breaks = as.character(sort(bands))) +
  coord_sf(crs = ALBERS,
           xlim = c(bb["xmin"], bb["xmax"]), ylim = c(bb["ymin"], bb["ymax"]),
           expand = FALSE) +
  labs(title = paste0("Drive-time access to sampled ENT practices",
                      if (PRELIM) " (preliminary)" else ""),
       subtitle = sprintf("Area within a 30/60/120/180-minute drive of any of %d practice locations%s",
                          length(unique(iso$loc_id)),
                          if (PRELIM) " — partial run" else "")) +
  theme_void(base_size = 12) +
  theme(legend.position = "bottom", legend.key.width = unit(1.4, "cm"),
        plot.title = element_text(face = "bold"),
        plot.margin = margin(6, 10, 6, 10)) +
  guides(fill = guide_legend(nrow = 1, label.position = "bottom"))
ggsave(file.path(outdir, paste0("figS7_ent_drivetime_coverage", suffix, ".png")), g,
       width = 9, height = 6.6, dpi = 150)
cat("\nWrote figS7_ent_drivetime_coverage", suffix, ".png + coverage stats\n", sep = "")
