#!/usr/bin/env Rscript
# =============================================================================
# Generate Methods + Results prose for the ENT access study using the study
# package's own text generators. Loads the FIXED source tree (devtools::load_all)
# rather than the stale installed build, so bug fixes (e.g. results_paragraph
# `subject` override) are in effect.
#
# Output: model_output/prose_mysterycall.md
# =============================================================================

suppressMessages(devtools::load_all("~/mysterycall", quiet = TRUE))
suppressPackageStartupMessages({library(dplyr)})
options(stringsAsFactors = FALSE, width = 100)
outdir <- "model_output"; dir.create(outdir, showWarnings = FALSE)
num <- function(x) suppressWarnings(as.numeric(x))

d <- read.csv("data/processed/ent_phase2_enriched.csv", colClasses = "character")
d <- d[d$complete == "Complete" & d$ent_type != "" & !is.na(d$ent_type), ]
d$offered   <- ifelse(d$appointment_offered == "TRUE", 1L, 0L)
d$wait_days <- num(d$wait_days_business)
for (v in c("ent_per_100k","medicaid_fee_index","svi_overall","dual_pct"))
  d[[paste0(v,"_z")]] <- { x<-num(d[[v]]); x[is.na(x)]<-median(x,na.rm=TRUE); as.numeric(scale(x)) }
d$ent_type <- relevel(factor(d$ent_type), ref = "General")
d$rural    <- relevel(factor(d$ruca_category), ref = "Urban")
ct <- table(d$caller); d$caller_f <- relevel(factor(ifelse(d$caller %in% names(ct)[ct<15],"Other",d$caller)),
                                              ref = names(sort(ct,decreasing=TRUE))[1])
clust <- d$cbsa_code; clust[!nzchar(clust)] <- d$county_fips[!nzchar(clust)]
clust[!nzchar(clust)] <- paste0("solo_", which(!nzchar(clust))); d$cluster <- clust
preds <- c("ent_type","ent_per_100k_z","medicaid_fee_index_z","svi_overall_z","dual_pct_z","rural","caller_f")

acc  <- mysterycall_logistic_model(d[!is.na(d$offered),], "offered", preds, "cluster")
d2   <- d[which(d$offered==1 & !is.na(d$wait_days)),]
wait <- mysterycall_nb_model(d2, "wait_days", preds, "cluster")

emit <- function(x) if (is.null(x)) "[generator returned NULL]" else paste(x, collapse = " ")

# ---- METHODS ----------------------------------------------------------------
methods <- tryCatch(mysterycall_methods_paragraph(
  n_physicians   = nrow(d),
  n_cities       = length(unique(d$city)),
  specialties    = levels(d$ent_type),
  insurance_types = NULL,
  outcome        = "business days until the next available new-patient appointment",
  software       = "R 4.4.2",
  model_family   = "negative_binomial"), error = function(e) paste("[methods_paragraph error:", conditionMessage(e), "]"))

# ---- RESULTS ----------------------------------------------------------------
res_access <- tryCatch(mysterycall_results_paragraph(
  acc, exposure_col = "ent_type", ref_group = "General",
  outcome_label = "an appointment",
  subject = "requested-subspecialty calls"), error = function(e) paste("[results_paragraph error:", conditionMessage(e), "]"))

wait_obj  <- tryCatch(mysterycall_wait_time_sentence(
  d2, outcome_col = "wait_days", group_col = "rural",
  reference = "Urban"), error = function(e) NULL)
wait_desc <- if (!is.null(wait_obj)) wait_obj$sentence else "[wait_time_sentence error]"

od_obj  <- tryCatch(mysterycall_overdispersion_sentence(wait$model), error = function(e) NULL)
od_sent <- if (!is.null(od_obj)) od_obj$sentence else "[overdispersion_sentence error]"

# mysterycall_icc requires an nb/poisson model object -> timeliness ICC
icc_obj  <- tryCatch(mysterycall_icc(wait), error = function(e) NULL)
icc_sent <- if (!is.null(icc_obj)) tryCatch(mysterycall_icc_sentence(icc_obj),
              error = function(e) paste("[icc_sentence error:", conditionMessage(e), "]")) else "[icc unavailable]"
# access ICC by hand (logistic latent scale)
va <- as.numeric(glmmTMB::VarCorr(acc$model)$cond$cluster)
acc_icc <- va / (va + pi^2/3)

base_wait <- mean(d2$wait_days[d2$ent_type=="General"], na.rm=TRUE)
days <- tryCatch(mysterycall_irr_to_days(wait, baseline_mean = base_wait,
          exposure_col = "ent_type", ref_group = "General",
          subject = "requested-subspecialty calls"), error = function(e) NULL)
# WORKAROUND for live bug #2: irr_to_days still hardcodes the "-insured" infix.
days_sentences <- if (!is.null(days$sentences))
  gsub("-insured requested-subspecialty calls", " calls", days$sentences) else NULL

# ---- ASSEMBLE ---------------------------------------------------------------
out <- c(
  "# Methods and Results — generated by mysterycall",
  "",
  "> Auto-generated via the study package's text generators from the fitted",
  "> models. Review wording: these generators are templated for the insurance-",
  "> exposure OB/GYN study, so some phrasing is generic for a subspecialty design.",
  "",
  "## Methods (mysterycall_methods_paragraph)", "", emit(methods), "",
  "## Results", "",
  "### Access (mysterycall_results_paragraph, subject overridden)", "", emit(res_access), "",
  "### Timeliness — descriptive (mysterycall_wait_time_sentence)", "", emit(wait_desc), "",
  "### Timeliness — dispersion (mysterycall_overdispersion_sentence)", "", emit(od_sent), "",
  "### Timeliness clustering (mysterycall_icc_sentence, wait model)", "", emit(icc_sent), "",
  sprintf("Access-model market ICC (computed): %.1f%%.", 100*acc_icc), "",
  "### Subspecialty wait in absolute days (mysterycall_irr_to_days$sentences)", "",
  "> Note: `-insured` infix stripped as a workaround for live package bug #2.", "",
  if (!is.null(days_sentences)) paste("-", days_sentences) else "[irr_to_days returned NULL]"
)
writeLines(out, file.path(outdir, "prose_mysterycall.md"))
cat(paste(out, collapse = "\n"), "\n")
cat("\n\nWrote", file.path(outdir, "prose_mysterycall.md"), "\n")
